/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 03.09.2010, 08:57:34
 */

package muvibee;

import javax.swing.DefaultListModel;

/**
 *
 * @author bline
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        viewBooksComboBox.addActionListener(new ComboBoxActionListener(viewBooksLayeredPane));
        viewMusicComboBox.addActionListener(new ComboBoxActionListener(viewMusicLayeredPane));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        advancedSearchButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        languagesComboBox = new javax.swing.JComboBox();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        overviewPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        booksPanel = new javax.swing.JPanel();
        viewBooksPanel = new javax.swing.JPanel();
        viewBooksLayeredPane = new javax.swing.JLayeredPane();
        treeBooksScrollPane = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        CoverListBooksScrollPane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CoverDetailsListBooksScrollPane = new javax.swing.JScrollPane();
        DetailsListBooksScrollPane = new javax.swing.JScrollPane();
        viewBooksComboBox = new javax.swing.JComboBox();
        addBooksButton = new javax.swing.JButton();
        itemBooksScrollPane = new javax.swing.JScrollPane();
        itemBooksPanel = new javax.swing.JPanel();
        coverBookLabel = new javax.swing.JLabel();
        titleTextBookLabel = new javax.swing.JLabel();
        authorTextBookLabel = new javax.swing.JLabel();
        languageTextBookLabel = new javax.swing.JLabel();
        isbnTextBookLabel = new javax.swing.JLabel();
        genreTextBookLabel = new javax.swing.JLabel();
        locationTextBookLabel = new javax.swing.JLabel();
        eanTextBookLabel = new javax.swing.JLabel();
        releaseYearTextBookLabel = new javax.swing.JLabel();
        borrowedToTextBookLabel = new javax.swing.JLabel();
        borrowDateTextBookLabel = new javax.swing.JLabel();
        ratingBookPanel = new javax.swing.JPanel();
        oneRatingpointBookRadioButton = new javax.swing.JRadioButton();
        twoRatingpointsBookRadioButton = new javax.swing.JRadioButton();
        threeRatingpointsBookRadioButton = new javax.swing.JRadioButton();
        descriptionBookScrollPane = new javax.swing.JScrollPane();
        descriptionBookTextArea = new javax.swing.JTextArea();
        annotationBookScrollPane = new javax.swing.JScrollPane();
        annotationBookTextArea = new javax.swing.JTextArea();
        editBookButton = new javax.swing.JButton();
        deleteBookButton = new javax.swing.JButton();
        musicPanel = new javax.swing.JPanel();
        viewMusicPanel = new javax.swing.JPanel();
        viewMusicLayeredPane = new javax.swing.JLayeredPane();
        treeMusicScrollPane = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        CoverListMusicScrollPane = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        CoverDetailsListMusicScrollPane = new javax.swing.JScrollPane();
        DetailsListMusicScrollPane = new javax.swing.JScrollPane();
        viewMusicComboBox = new javax.swing.JComboBox();
        addMusicButton = new javax.swing.JButton();
        itemMusicScrollPane = new javax.swing.JScrollPane();
        itemMusicPanel = new javax.swing.JPanel();
        coverMusicLabel = new javax.swing.JLabel();
        titleTextMusicLabel = new javax.swing.JLabel();
        interpretTextMusicLabel = new javax.swing.JLabel();
        typeTextMusicLabel = new javax.swing.JLabel();
        formatTextMusicLabel = new javax.swing.JLabel();
        genreTextMusicLabel = new javax.swing.JLabel();
        locationTextMusicLabel = new javax.swing.JLabel();
        eanTextMusicLabel = new javax.swing.JLabel();
        releaseYearTextMusicLabel = new javax.swing.JLabel();
        borrowedToTextMusicLabel = new javax.swing.JLabel();
        borrowDateTextMusicLabel = new javax.swing.JLabel();
        ratingMusicPanel = new javax.swing.JPanel();
        oneRatingpointMusikRadioButton = new javax.swing.JRadioButton();
        twoRatingpointMusikRadioButton = new javax.swing.JRadioButton();
        threeRatingpointMusikRadioButton = new javax.swing.JRadioButton();
        descriptionMusicScrollPane = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        annotationMusicScrollPane = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        editMusicButton = new javax.swing.JButton();
        deleteMusicButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jComboBox4 = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchTextField.setText("jTextField1");

        searchButton.setText("Suchen");

        advancedSearchButton.setText("Erweiterte Suche");

        aboutButton.setText("Über");

        helpButton.setText("Hilfe");

        languagesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        languagesComboBox.setName("LangaugesComboBox"); // NOI18N

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(languagesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addContainerGap())
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(searchButton)
                    .addComponent(advancedSearchButton)
                    .addComponent(aboutButton)
                    .addComponent(helpButton)
                    .addComponent(languagesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        statusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        statusLabel.setText("jLabel1");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel35.setText("jLabel35");

        jLabel36.setText("jLabel36");

        jLabel37.setText("jLabel37");

        jLabel38.setText("jLabel38");

        jLabel39.setText("jLabel39");

        jLabel40.setText("jLabel40");

        jLabel41.setText("jLabel41");

        jLabel42.setText("jLabel42");

        jLabel43.setText("jLabel43");

        jLabel44.setText("jLabel44");

        jLabel45.setText("jLabel45");

        jLabel46.setText("jLabel46");

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)))
                    .addComponent(jLabel38)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)))
                    .addComponent(jLabel41)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)))
                    .addComponent(jLabel44)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45))))
                .addContainerGap(736, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Übersicht", overviewPanel);

        viewBooksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        treeBooksScrollPane.setName("Tree"); // NOI18N
        treeBooksScrollPane.setPreferredSize(new java.awt.Dimension(74, 322));
        treeBooksScrollPane.setViewportView(jTree1);

        treeBooksScrollPane.setBounds(0, 0, 217, 430);
        viewBooksLayeredPane.add(treeBooksScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CoverListBooksScrollPane.setName("Cover"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CoverListBooksScrollPane.setViewportView(jList1);

        CoverListBooksScrollPane.setBounds(0, 0, 217, 430);
        viewBooksLayeredPane.add(CoverListBooksScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CoverDetailsListBooksScrollPane.setName("Cover Details"); // NOI18N
        CoverDetailsListBooksScrollPane.setBounds(0, 0, 217, 430);
        viewBooksLayeredPane.add(CoverDetailsListBooksScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DetailsListBooksScrollPane.setName("Details"); // NOI18N
        DetailsListBooksScrollPane.setBounds(0, 0, 217, 430);
        viewBooksLayeredPane.add(DetailsListBooksScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewBooksComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tree", "Cover", "Cover Details", "Details" }));
        viewBooksComboBox.setName("ViewComboBox"); // NOI18N

        addBooksButton.setText("Hinzufügen");

        javax.swing.GroupLayout viewBooksPanelLayout = new javax.swing.GroupLayout(viewBooksPanel);
        viewBooksPanel.setLayout(viewBooksPanelLayout);
        viewBooksPanelLayout.setHorizontalGroup(
            viewBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBooksLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(viewBooksPanelLayout.createSequentialGroup()
                        .addComponent(viewBooksComboBox, 0, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBooksButton)))
                .addContainerGap())
        );
        viewBooksPanelLayout.setVerticalGroup(
            viewBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBooksPanelLayout.createSequentialGroup()
                .addComponent(viewBooksLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBooksButton)
                    .addComponent(viewBooksComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        coverBookLabel.setText("jLabel2");

        titleTextBookLabel.setText("Titel");

        authorTextBookLabel.setText("Autor");

        languageTextBookLabel.setText("Sprache");

        isbnTextBookLabel.setText("ISBN");

        genreTextBookLabel.setText("Genre");

        locationTextBookLabel.setText("Standort");

        eanTextBookLabel.setText("EAN");

        releaseYearTextBookLabel.setText("Erscheinungsjahr");

        borrowedToTextBookLabel.setText("Verliehen");

        borrowDateTextBookLabel.setText("Verleihdatum");

        ratingBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bewertung"));

        buttonGroup1.add(oneRatingpointBookRadioButton);
        oneRatingpointBookRadioButton.setText("1");
        oneRatingpointBookRadioButton.setActionCommand("jRadioButton1");

        buttonGroup1.add(twoRatingpointsBookRadioButton);
        twoRatingpointsBookRadioButton.setText("2");

        buttonGroup1.add(threeRatingpointsBookRadioButton);
        threeRatingpointsBookRadioButton.setText("3");

        javax.swing.GroupLayout ratingBookPanelLayout = new javax.swing.GroupLayout(ratingBookPanel);
        ratingBookPanel.setLayout(ratingBookPanelLayout);
        ratingBookPanelLayout.setHorizontalGroup(
            ratingBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oneRatingpointBookRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoRatingpointsBookRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeRatingpointsBookRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ratingBookPanelLayout.setVerticalGroup(
            ratingBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneRatingpointBookRadioButton)
                    .addComponent(twoRatingpointsBookRadioButton)
                    .addComponent(threeRatingpointsBookRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        descriptionBookScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Beschreibung"));

        descriptionBookTextArea.setColumns(20);
        descriptionBookTextArea.setRows(5);
        descriptionBookScrollPane.setViewportView(descriptionBookTextArea);

        annotationBookScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Kommentar"));

        annotationBookTextArea.setColumns(20);
        annotationBookTextArea.setRows(5);
        annotationBookScrollPane.setViewportView(annotationBookTextArea);

        editBookButton.setText("Bearbeiten");

        deleteBookButton.setText("Löschen");

        javax.swing.GroupLayout itemBooksPanelLayout = new javax.swing.GroupLayout(itemBooksPanel);
        itemBooksPanel.setLayout(itemBooksPanelLayout);
        itemBooksPanelLayout.setHorizontalGroup(
            itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemBooksPanelLayout.createSequentialGroup()
                        .addComponent(editBookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBookButton))
                    .addComponent(annotationBookScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(descriptionBookScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(itemBooksPanelLayout.createSequentialGroup()
                        .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coverBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTextBookLabel)
                            .addComponent(authorTextBookLabel)
                            .addComponent(languageTextBookLabel)
                            .addComponent(isbnTextBookLabel)
                            .addComponent(eanTextBookLabel)
                            .addComponent(genreTextBookLabel)
                            .addComponent(releaseYearTextBookLabel)
                            .addComponent(borrowDateTextBookLabel)
                            .addComponent(borrowedToTextBookLabel)
                            .addComponent(locationTextBookLabel))))
                .addContainerGap())
        );
        itemBooksPanelLayout.setVerticalGroup(
            itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBookButton)
                    .addComponent(editBookButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemBooksPanelLayout.createSequentialGroup()
                        .addComponent(titleTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(languageTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eanTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genreTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(releaseYearTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationTextBookLabel))
                    .addComponent(coverBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(itemBooksPanelLayout.createSequentialGroup()
                        .addComponent(borrowedToTextBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowDateTextBookLabel))
                    .addComponent(ratingBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionBookScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annotationBookScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        itemBooksScrollPane.setViewportView(itemBooksPanel);

        javax.swing.GroupLayout booksPanelLayout = new javax.swing.GroupLayout(booksPanel);
        booksPanel.setLayout(booksPanelLayout);
        booksPanelLayout.setHorizontalGroup(
            booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemBooksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        booksPanelLayout.setVerticalGroup(
            booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemBooksScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(viewBooksPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Bücher", booksPanel);

        viewMusicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        treeMusicScrollPane.setName("Tree"); // NOI18N
        treeMusicScrollPane.setViewportView(jTree2);

        treeMusicScrollPane.setBounds(0, 0, 217, 430);
        viewMusicLayeredPane.add(treeMusicScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CoverListMusicScrollPane.setName("Cover"); // NOI18N

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CoverListMusicScrollPane.setViewportView(jList2);

        CoverListMusicScrollPane.setBounds(0, 0, 217, 430);
        viewMusicLayeredPane.add(CoverListMusicScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CoverDetailsListMusicScrollPane.setName("Cover Details"); // NOI18N
        CoverDetailsListMusicScrollPane.setBounds(0, 0, 217, 430);
        viewMusicLayeredPane.add(CoverDetailsListMusicScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DetailsListMusicScrollPane.setName("Details"); // NOI18N
        DetailsListMusicScrollPane.setBounds(0, 0, 217, 430);
        viewMusicLayeredPane.add(DetailsListMusicScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewMusicComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tree", "Cover", "Cover Details", "Details" }));
        viewMusicComboBox.setName("ViewComboBox"); // NOI18N

        addMusicButton.setText("Hinzufügen");

        javax.swing.GroupLayout viewMusicPanelLayout = new javax.swing.GroupLayout(viewMusicPanel);
        viewMusicPanel.setLayout(viewMusicPanelLayout);
        viewMusicPanelLayout.setHorizontalGroup(
            viewMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMusicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewMusicLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(viewMusicPanelLayout.createSequentialGroup()
                        .addComponent(viewMusicComboBox, 0, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMusicButton)))
                .addContainerGap())
        );
        viewMusicPanelLayout.setVerticalGroup(
            viewMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMusicPanelLayout.createSequentialGroup()
                .addComponent(viewMusicLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addMusicButton)
                    .addComponent(viewMusicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        itemMusicPanel.setPreferredSize(new java.awt.Dimension(539, 768));

        coverMusicLabel.setText("jLabel2");

        titleTextMusicLabel.setText("Titel");

        interpretTextMusicLabel.setText("Interpret");

        typeTextMusicLabel.setText("Typ");

        formatTextMusicLabel.setText("Format");

        genreTextMusicLabel.setText("Genre");

        locationTextMusicLabel.setText("Standort");

        eanTextMusicLabel.setText("EAN");

        releaseYearTextMusicLabel.setText("Erscheinungsjahr");

        borrowedToTextMusicLabel.setText("Verliehen");

        borrowDateTextMusicLabel.setText("Verleihdatum");

        ratingMusicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bewertung"));

        buttonGroup1.add(oneRatingpointMusikRadioButton);
        oneRatingpointMusikRadioButton.setText("1");
        oneRatingpointMusikRadioButton.setActionCommand("jRadioButton1");

        buttonGroup1.add(twoRatingpointMusikRadioButton);
        twoRatingpointMusikRadioButton.setText("2");

        buttonGroup1.add(threeRatingpointMusikRadioButton);
        threeRatingpointMusikRadioButton.setText("3");

        javax.swing.GroupLayout ratingMusicPanelLayout = new javax.swing.GroupLayout(ratingMusicPanel);
        ratingMusicPanel.setLayout(ratingMusicPanelLayout);
        ratingMusicPanelLayout.setHorizontalGroup(
            ratingMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingMusicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oneRatingpointMusikRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoRatingpointMusikRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeRatingpointMusikRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ratingMusicPanelLayout.setVerticalGroup(
            ratingMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingMusicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneRatingpointMusikRadioButton)
                    .addComponent(twoRatingpointMusikRadioButton)
                    .addComponent(threeRatingpointMusikRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        descriptionMusicScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Beschreibung"));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        descriptionMusicScrollPane.setViewportView(jTextArea3);

        annotationMusicScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Kommentar"));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        annotationMusicScrollPane.setViewportView(jTextArea4);

        editMusicButton.setText("Bearbeiten");

        deleteMusicButton.setText("Löschen");

        javax.swing.GroupLayout itemMusicPanelLayout = new javax.swing.GroupLayout(itemMusicPanel);
        itemMusicPanel.setLayout(itemMusicPanelLayout);
        itemMusicPanelLayout.setHorizontalGroup(
            itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMusicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemMusicPanelLayout.createSequentialGroup()
                        .addComponent(editMusicButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteMusicButton))
                    .addComponent(annotationMusicScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(descriptionMusicScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(itemMusicPanelLayout.createSequentialGroup()
                        .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coverMusicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingMusicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTextMusicLabel)
                            .addComponent(interpretTextMusicLabel)
                            .addComponent(typeTextMusicLabel)
                            .addComponent(formatTextMusicLabel)
                            .addComponent(eanTextMusicLabel)
                            .addComponent(genreTextMusicLabel)
                            .addComponent(releaseYearTextMusicLabel)
                            .addComponent(borrowDateTextMusicLabel)
                            .addComponent(borrowedToTextMusicLabel)
                            .addComponent(locationTextMusicLabel))))
                .addContainerGap())
        );
        itemMusicPanelLayout.setVerticalGroup(
            itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMusicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editMusicButton)
                    .addComponent(deleteMusicButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemMusicPanelLayout.createSequentialGroup()
                        .addComponent(titleTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(interpretTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eanTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genreTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(releaseYearTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationTextMusicLabel))
                    .addComponent(coverMusicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemMusicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(itemMusicPanelLayout.createSequentialGroup()
                        .addComponent(borrowedToTextMusicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowDateTextMusicLabel))
                    .addComponent(ratingMusicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionMusicScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annotationMusicScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        itemMusicScrollPane.setViewportView(itemMusicPanel);

        javax.swing.GroupLayout musicPanelLayout = new javax.swing.GroupLayout(musicPanel);
        musicPanel.setLayout(musicPanelLayout);
        musicPanelLayout.setHorizontalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewMusicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemMusicScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        musicPanelLayout.setVerticalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemMusicScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(viewMusicPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Musik", musicPanel);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane15.setBounds(0, 0, 217, 430);
        jLayeredPane3.add(jScrollPane15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jScrollPane16.setBounds(0, 0, 217, 430);
        jLayeredPane3.add(jScrollPane16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jScrollPane17.setBounds(0, 0, 217, 430);
        jLayeredPane3.add(jScrollPane17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jScrollPane18.setBounds(0, 0, 217, 430);
        jLayeredPane3.add(jScrollPane18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton11.setText("Hinzufügen");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jComboBox4, 0, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel14.setPreferredSize(new java.awt.Dimension(539, 768));

        jLabel24.setText("jLabel2");

        jLabel25.setText("Titel");

        jLabel26.setText("Regisseur");

        jLabel27.setText("Schauspieler");

        jLabel28.setText("Format");

        jLabel29.setText("Genre");

        jLabel30.setText("Standort");

        jLabel31.setText("EAN");

        jLabel32.setText("Erscheinungsjahr");

        jLabel33.setText("Verliehen");

        jLabel34.setText("Verleihdatum");

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Bewertung"));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("1");
        jRadioButton7.setActionCommand("jRadioButton1");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("2");

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("3");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane20.setBorder(javax.swing.BorderFactory.createTitledBorder("Beschreibung"));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane20.setViewportView(jTextArea5);

        jScrollPane21.setBorder(javax.swing.BorderFactory.createTitledBorder("Kommentar"));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane21.setViewportView(jTextArea6);

        jButton12.setText("Bearbeiten");

        jButton13.setText("Löschen");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13))
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30))
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane19.setViewportView(jPanel14);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Videos", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            DefaultListModel dlm = new DefaultListModel();
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CoverDetailsListBooksScrollPane;
    private javax.swing.JScrollPane CoverDetailsListMusicScrollPane;
    private javax.swing.JScrollPane CoverListBooksScrollPane;
    private javax.swing.JScrollPane CoverListMusicScrollPane;
    private javax.swing.JScrollPane DetailsListBooksScrollPane;
    private javax.swing.JScrollPane DetailsListMusicScrollPane;
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton addBooksButton;
    private javax.swing.JButton addMusicButton;
    private javax.swing.JButton advancedSearchButton;
    private javax.swing.JScrollPane annotationBookScrollPane;
    private javax.swing.JTextArea annotationBookTextArea;
    private javax.swing.JScrollPane annotationMusicScrollPane;
    private javax.swing.JLabel authorTextBookLabel;
    private javax.swing.JPanel booksPanel;
    private javax.swing.JLabel borrowDateTextBookLabel;
    private javax.swing.JLabel borrowDateTextMusicLabel;
    private javax.swing.JLabel borrowedToTextBookLabel;
    private javax.swing.JLabel borrowedToTextMusicLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel coverBookLabel;
    private javax.swing.JLabel coverMusicLabel;
    private javax.swing.JButton deleteBookButton;
    private javax.swing.JButton deleteMusicButton;
    private javax.swing.JScrollPane descriptionBookScrollPane;
    private javax.swing.JTextArea descriptionBookTextArea;
    private javax.swing.JScrollPane descriptionMusicScrollPane;
    private javax.swing.JLabel eanTextBookLabel;
    private javax.swing.JLabel eanTextMusicLabel;
    private javax.swing.JButton editBookButton;
    private javax.swing.JButton editMusicButton;
    private javax.swing.JLabel formatTextMusicLabel;
    private javax.swing.JLabel genreTextBookLabel;
    private javax.swing.JLabel genreTextMusicLabel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel interpretTextMusicLabel;
    private javax.swing.JLabel isbnTextBookLabel;
    private javax.swing.JPanel itemBooksPanel;
    private javax.swing.JScrollPane itemBooksScrollPane;
    private javax.swing.JPanel itemMusicPanel;
    private javax.swing.JScrollPane itemMusicScrollPane;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JLabel languageTextBookLabel;
    private javax.swing.JComboBox languagesComboBox;
    private javax.swing.JLabel locationTextBookLabel;
    private javax.swing.JLabel locationTextMusicLabel;
    private javax.swing.JPanel musicPanel;
    private javax.swing.JRadioButton oneRatingpointBookRadioButton;
    private javax.swing.JRadioButton oneRatingpointMusikRadioButton;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JPanel ratingBookPanel;
    private javax.swing.JPanel ratingMusicPanel;
    private javax.swing.JLabel releaseYearTextBookLabel;
    private javax.swing.JLabel releaseYearTextMusicLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JRadioButton threeRatingpointMusikRadioButton;
    private javax.swing.JRadioButton threeRatingpointsBookRadioButton;
    private javax.swing.JLabel titleTextBookLabel;
    private javax.swing.JLabel titleTextMusicLabel;
    private javax.swing.JScrollPane treeBooksScrollPane;
    private javax.swing.JScrollPane treeMusicScrollPane;
    private javax.swing.JRadioButton twoRatingpointMusikRadioButton;
    private javax.swing.JRadioButton twoRatingpointsBookRadioButton;
    private javax.swing.JLabel typeTextMusicLabel;
    private javax.swing.JComboBox viewBooksComboBox;
    private javax.swing.JLayeredPane viewBooksLayeredPane;
    private javax.swing.JPanel viewBooksPanel;
    private javax.swing.JComboBox viewMusicComboBox;
    private javax.swing.JLayeredPane viewMusicLayeredPane;
    private javax.swing.JPanel viewMusicPanel;
    // End of variables declaration//GEN-END:variables

}
