/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvancedSearchDialog.java
 *
 * Created on Sep 16, 2010, 10:39:25 PM
 */

package muvibee.gui;

import muvibee.media.Book;
import muvibee.media.Music;
import muvibee.media.Video;
import muvibee.utils.NonValidYearException;
import muvibee.utils.TestUtils;

/**
 *
 * @author tim
 */
public class AdvancedSearchDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    public static final int RET_ILLEGAL_YEAR = -1;

    private Book book;
    private Music music;
    private Video video;

    public AdvancedSearchDialog(java.awt.Frame parent,String title, boolean modal){
        super(parent, title, modal);
        initComponents();
    }

    /** Creates new form AdvancedSearchDialog */
    public AdvancedSearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    public Book getBook() {
        return book;
    }

    public Music getMusic() {
        return music;
    }

    public Video getVideo() {
        return video;
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingButtonGroup = new javax.swing.ButtonGroup();
        mediaPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        eanLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        releaseYearLabel = new javax.swing.JLabel();
        lentToLabel = new javax.swing.JLabel();
        lentDateLabel = new javax.swing.JLabel();
        lentUntilDateLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        annotationLabel = new javax.swing.JLabel();
        ratingOneRadioButton = new javax.swing.JRadioButton();
        ratingTwoRadioButton = new javax.swing.JRadioButton();
        ratingThreeRadioButton = new javax.swing.JRadioButton();
        titleTextField = new javax.swing.JTextField();
        eanTextField = new javax.swing.JTextField();
        genreTextField = new javax.swing.JTextField();
        lentToTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        annotationTextField = new javax.swing.JTextField();
        releaseYearComboBox = new javax.swing.JComboBox();
        lentDayComboBox = new javax.swing.JComboBox();
        lentMonthComboBox = new javax.swing.JComboBox();
        lentYearComboBox = new javax.swing.JComboBox();
        lentUntilDayComboBox = new javax.swing.JComboBox();
        lentUntilMonthComboBox = new javax.swing.JComboBox();
        lentUntilYearComboBox = new javax.swing.JComboBox();
        bookPanel = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        languageLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        languageTextField = new javax.swing.JTextField();
        isbnTextField = new javax.swing.JTextField();
        musicPanel = new javax.swing.JPanel();
        artistLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        musikFormatLabel = new javax.swing.JLabel();
        artistTextField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox();
        musicFormatComboBox = new javax.swing.JComboBox();
        videoPanel = new javax.swing.JPanel();
        directorLabel = new javax.swing.JLabel();
        actorsLabel = new javax.swing.JLabel();
        videoFormatLabel = new javax.swing.JLabel();
        directorTextField = new javax.swing.JTextField();
        actorsTextField = new javax.swing.JTextField();
        videoFormatComboBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mediaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Allgmeine Daten"));

        titleLabel.setText("Titel");

        ratingLabel.setText("Bewertung");

        eanLabel.setText("EAN");

        genreLabel.setText("Genre");

        releaseYearLabel.setText("Erscheinungsjahr");

        lentToLabel.setText("Verliehen an");

        lentDateLabel.setText("Verleihdatum");

        lentUntilDateLabel.setText("Verliehen bis");

        locationLabel.setText("Standort");

        annotationLabel.setText("Kommentar");

        ratingButtonGroup.add(ratingOneRadioButton);
        ratingOneRadioButton.setText("1");

        ratingButtonGroup.add(ratingTwoRadioButton);
        ratingTwoRadioButton.setText("2");

        ratingButtonGroup.add(ratingThreeRadioButton);
        ratingThreeRadioButton.setText("3");

        lentYearComboBox.setEditable(true);

        lentUntilYearComboBox.setEditable(true);

        javax.swing.GroupLayout mediaPanelLayout = new javax.swing.GroupLayout(mediaPanel);
        mediaPanel.setLayout(mediaPanelLayout);
        mediaPanelLayout.setHorizontalGroup(
            mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mediaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(ratingLabel)
                    .addComponent(eanLabel)
                    .addComponent(genreLabel)
                    .addComponent(releaseYearLabel))
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genreTextField)
                            .addComponent(eanTextField)
                            .addGroup(mediaPanelLayout.createSequentialGroup()
                                .addComponent(ratingOneRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingTwoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingThreeRadioButton))
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(releaseYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lentToLabel)
                    .addComponent(lentDateLabel)
                    .addComponent(locationLabel)
                    .addComponent(lentUntilDateLabel)
                    .addComponent(annotationLabel))
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mediaPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lentToTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(locationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(annotationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mediaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentMonthComboBox, 0, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentUntilDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentUntilMonthComboBox, 0, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lentUntilYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mediaPanelLayout.setVerticalGroup(
            mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mediaPanelLayout.createSequentialGroup()
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ratingOneRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ratingTwoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ratingThreeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eanLabel)
                            .addComponent(eanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(releaseYearLabel)
                            .addComponent(annotationLabel)
                            .addComponent(annotationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(releaseYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lentToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lentToLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lentDateLabel)
                            .addComponent(lentDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lentMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lentYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lentUntilDateLabel)
                            .addComponent(lentUntilDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lentUntilMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lentUntilYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bücher"));

        authorLabel.setText("Autor");

        languageLabel.setText("Sprache");

        isbnLabel.setText("ISBN");

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addComponent(languageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isbnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageTextField)
                    .addComponent(isbnTextField)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        musicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Musik"));

        artistLabel.setText("Interpret");

        typeLabel.setText("Typ");

        musikFormatLabel.setText("Format");

        typeComboBox.setEditable(true);

        musicFormatComboBox.setEditable(true);

        javax.swing.GroupLayout musicPanelLayout = new javax.swing.GroupLayout(musicPanel);
        musicPanel.setLayout(musicPanelLayout);
        musicPanelLayout.setHorizontalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artistLabel)
                    .addComponent(typeLabel)
                    .addComponent(musikFormatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeComboBox, 0, 160, Short.MAX_VALUE)
                    .addComponent(artistTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(musicFormatComboBox, 0, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        musicPanelLayout.setVerticalGroup(
            musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicPanelLayout.createSequentialGroup()
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistLabel)
                    .addComponent(artistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(musicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musikFormatLabel)
                    .addComponent(musicFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        videoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Videos"));

        directorLabel.setText("Regisseur");

        actorsLabel.setText("Schauspieler");

        videoFormatLabel.setText("Format");

        videoFormatComboBox.setEditable(true);

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(videoFormatLabel)
                    .addComponent(actorsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actorsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(directorTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(videoFormatComboBox, 0, 171, Short.MAX_VALUE))
                .addContainerGap())
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directorLabel)
                    .addComponent(directorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actorsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actorsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoFormatLabel)
                    .addComponent(videoFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchButton.setText("Suchen");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(musicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mediaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(videoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchButton)
                            .addComponent(cancelButton)))
                    .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int returnCode = RET_OK;

        String title = titleTextField.getText().trim();
        String ean = eanTextField.getText().trim();	    //TODO Ueberpruefen!?!?
        String genre = genreTextField.getText().trim();
        Object selectedReleaseYear = releaseYearComboBox.getSelectedItem();
        String releaseYear = "";
        if(selectedReleaseYear != null)
            releaseYear = selectedReleaseYear.toString().trim();
        String location = locationTextField.getText().trim();
        String lendTo = lentToTextField.getText().trim();
        int lendDay = lentDayComboBox.getSelectedIndex();
        int lendMonth = lentMonthComboBox.getSelectedIndex();
        Object selectedLentYear = lentYearComboBox.getSelectedItem();
        String lentYear = "";
        if(selectedLentYear != null)
            lentYear = selectedLentYear.toString().trim();
        int lendUntilDay = lentUntilDayComboBox.getSelectedIndex();
        int lendUntilMonth = lentUntilMonthComboBox.getSelectedIndex();
        Object selectedLentUntilYear = lentUntilYearComboBox.getSelectedItem();
        String lentUntilYear = "";
        if(selectedLentUntilYear != null)
            lentUntilYear = selectedLentUntilYear.toString().trim();
        String annotation = annotationTextField.getText().trim();
        
        //Rating
        int rating = 0;
        if (ratingOneRadioButton.isSelected()) {
            rating = 1;
        } else if (ratingOneRadioButton.isSelected()) {
            rating = 2;
        } else if (ratingOneRadioButton.isSelected()) {
            rating = 3;
        }

        String author = authorTextField.getText().trim();
        String language = languageTextField.getText().trim();
        String isbn = isbnTextField.getText().trim();   //TODO Ueberpruefen!?!?

        String artist = artistTextField.getText().trim();
        Object selectedType = typeComboBox.getSelectedItem();
        String type = "";
        if(selectedType != null)
            type = selectedType.toString().trim();
        Object selectedMusicFormat = musicFormatComboBox.getSelectedItem();
        String musicFormat = "";
        if(selectedMusicFormat != null)
            musicFormat = selectedMusicFormat.toString().trim();

        String director = directorTextField.getText().trim();
        String actors = actorsTextField.getText().trim();
        Object selectedVideoFormat = videoFormatComboBox.getSelectedItem();
        String videoFormat = "";
        if (selectedVideoFormat != null) {
            videoFormat = selectedVideoFormat.toString().trim();
        }


        try {
            int ry = TestUtils.validYear(releaseYear);
            int ly = TestUtils.validYear(lentYear);
            int luy = TestUtils.validYear(lentUntilYear);
            book = new Book();
            book.setTitle(title);
            book.setAuthor(author);
            book.setLanguage(language);
            book.setIsbn(isbn);
            book.setEan(ean);
            book.setGenre(genre);
            book.setReleaseYear(ry);
            book.setLocation(location);
            book.setLendTo(lendTo);
            book.setLendDay(lendDay);
            book.setLendMonth(lendMonth);
            book.setLendYear(ly);
            book.setLendUntilDay(lendUntilDay);
            book.setLendUntilMonth(lendUntilMonth);
            book.setLendUntilYear(luy);
            book.setRating(rating);
            book.setComment(annotation);

            music = new Music();
            music.setTitle(title);
            music.setInterpreter(artist);
            music.setType(type);
            music.setFormat(musicFormat);
            music.setEan(ean);
            music.setGenre(genre);
            music.setReleaseYear(ry);
            music.setLocation(location);
            music.setLendTo(lendTo);
            music.setLendDay(lendDay);
            music.setLendMonth(lendMonth);
            music.setLendYear(ly);
            music.setLendUntilDay(lendUntilDay);
            music.setLendUntilMonth(lendUntilMonth);
            music.setLendUntilYear(luy);
            music.setRating(rating);
            music.setComment(annotation);

            video = new Video();
            video.setTitle(title);
            video.setDirector(director);
            video.setActors(actors);
            video.setFormat(videoFormat);
            video.setEan(ean);
            video.setGenre(genre);
            video.setReleaseYear(ry);
            video.setLocation(location);
            video.setLendTo(lendTo);
            video.setLendDay(lendDay);
            video.setLendMonth(lendMonth);
            video.setLendYear(ly);
            video.setLendUntilDay(lendUntilDay);
            video.setLendUntilMonth(lendUntilMonth);
            video.setLendUntilYear(luy);
            video.setRating(rating);
            video.setComment(annotation);
        } catch (NonValidYearException e) {
            returnCode = RET_ILLEGAL_YEAR;
        }

        doClose(returnCode);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actorsLabel;
    private javax.swing.JTextField actorsTextField;
    private javax.swing.JLabel annotationLabel;
    private javax.swing.JTextField annotationTextField;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JTextField artistTextField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel directorLabel;
    private javax.swing.JTextField directorTextField;
    private javax.swing.JLabel eanLabel;
    private javax.swing.JTextField eanTextField;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JTextField languageTextField;
    private javax.swing.JLabel lentDateLabel;
    private javax.swing.JComboBox lentDayComboBox;
    private javax.swing.JComboBox lentMonthComboBox;
    private javax.swing.JLabel lentToLabel;
    private javax.swing.JTextField lentToTextField;
    private javax.swing.JLabel lentUntilDateLabel;
    private javax.swing.JComboBox lentUntilDayComboBox;
    private javax.swing.JComboBox lentUntilMonthComboBox;
    private javax.swing.JComboBox lentUntilYearComboBox;
    private javax.swing.JComboBox lentYearComboBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JPanel mediaPanel;
    private javax.swing.JComboBox musicFormatComboBox;
    private javax.swing.JPanel musicPanel;
    private javax.swing.JLabel musikFormatLabel;
    private javax.swing.ButtonGroup ratingButtonGroup;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JRadioButton ratingOneRadioButton;
    private javax.swing.JRadioButton ratingThreeRadioButton;
    private javax.swing.JRadioButton ratingTwoRadioButton;
    private javax.swing.JComboBox releaseYearComboBox;
    private javax.swing.JLabel releaseYearLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox videoFormatComboBox;
    private javax.swing.JLabel videoFormatLabel;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
